### ISSUE TITLE
As a user, I want to be able to provision an SSH key using only an existing public key

### ISSUE THREAD

**Issue by jvallexm** [cloud-native-toolkit/terraform-ibm-vpc-ssh#16]
As a user, I want to be able to provision an SSH key using only an existing public key. This is basic functionality of the `ibm_is_ssh_key` block

**Comment by seansund** [comment]
Fixed in [Release v1.6.0](https://github.com/cloud-native-toolkit/terraform-ibm-vpc-ssh/releases/tag/v1.6.0)
